---
title: "2_pyx_therm_sample
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
samp_data_prototypeT <- read_csv("samp_data-prototypeT.csv")
View(samp_data_prototypeT)


samp_data_prototypeT <- mutate(samp_data_prototypeT,X_Fe_CPX=Nb_ions_Fe_CPX/(Nb_ions_Fe_CPX+Nb_ions_Mg_CPX)) 
samp_data_prototypeT

samp_data_prototypeT <- mutate(samp_data_prototypeT,X_Fe_OPX=Nb_ions_Fe_OPX/(Nb_ions_Fe_OPX+Nb_ions_Mg_OPX))
samp_data_prototypeT

samp_data_prototypeT <- mutate(samp_data_prototypeT,Ca_star_CPX=Nb_ions_Ca_CPX/(1-Nb_ions_Na_CPX))
samp_data_prototypeT

samp_data_prototypeT <- mutate(samp_data_prototypeT,Ca_star_OPX=Nb_ions_Ca_OPX/(1-Nb_ions_Na_OPX))
samp_data_prototypeT

samp_data_prototypeT <- mutate(samp_data_prototypeT,K_sub_D=(1-Ca_star_CPX)/(1-Ca_star_OPX))
samp_data_prototypeT

samp_data_prototypeT <- mutate(samp_data_prototypeT,T_bacon_numerator=23664+(24.9+(126.3*X_Fe_CPX)))
samp_data_prototypeT 

samp_data_prototypeT <- mutate(samp_data_prototypeT,ln_K_sub_D=log(K_sub_D))
samp_data_prototypeT

samp_data_prototypeT <- mutate(samp_data_prototypeT,ln_K_sub_D_SQRD=ln_K_sub_D^2)
samp_data_prototypeT

samp_data_prototypeT <- mutate(samp_data_prototypeT,T_bacon_denominator=13.38+ln_K_sub_D_SQRD+(11.59*X_Fe_OPX))
samp_data_prototypeT

samp_data_prototypeT <- mutate(samp_data_prototypeT,Temp_Kelvins=T_bacon_numerator/T_bacon_denominator)
samp_data_prototypeT

samp_data_prototypeT <- mutate(samp_data_prototypeT,Temp_Celsius=Temp_Kelvins-273.15)
samp_data_prototypeT




```

